### ISSUE TITLE
Failure at the computing local genetic covariance step

### ISSUE THREAD

**Issue by udube** [qlu-lab/SUPERGNOVA#1]
Hello,

Thanks so much for providing this update to GNOVA! I've attempted to run supergnova.py with two input files that gnova.py can handle with no issues. 

Here is the command I am running: 

python3.6 supergnova.py /home/dubeu/SumStatAnalyses/GNOVA/sumstats1_nomissing /home/dubeu/SumStatAnalyses/GNOVA/sumstats2_nomissing --N1 800000 --N2 40000 --bfile data/bfiles/eur_chr@_SNPmaf5 --partition data/partition/eur_chr@.bed --out results.txt

Here is the error I am getting: 
...
Computed local genetic covariance for chromosome 11
Computed local genetic covariance for chromosome 12
Traceback (most recent call last):
  File "supergnova.py", line 91, in <module>
    pipeline(parser.parse_args())
  File "supergnova.py", line 63, in pipeline
    out = calculate(args.bfile, bed, args.thread, gwas_snps, N1, N2, h_1, h_2, pheno_corr, pheno_corr_var)
  File "/home/dubeu/SumStatAnalyses/SUPERGNOVA/calculate.py", line 177, in calculate
    all_dfs.append(_supergnova(cur_bfile, partition, thread, gwas_snps, n1, n2, h1, h2, pheno_corr, pheno_corr_var))
  File "/home/dubeu/SumStatAnalyses/SUPERGNOVA/calculate.py", line 155, in _supergnova
    df = pd.concat(results, ignore_index=True)
  File "/home/dubeu/.local/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 281, in concat
    sort=sort,
  File "/home/dubeu/.local/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 329, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by udube** [comment]
As an FYI, I get the same error when running with --thread 1

**Comment by YiliangTracyZhang** [comment]
> As an FYI, I get the same error when running with --thread 1

Thank you for your comment. We just noticed this and We are trying to fix this. we will keep you posted whenever the code is updated.

**Comment by YiliangTracyZhang** [comment]
Hi, I fixed the problem. Now, you will not have this error. Thank you.

**Comment by udube** [comment]
Great, thank you! I can confirm that the program runs through.
