### ISSUE TITLE
Global genetic covariance estimation

### ISSUE THREAD

**Issue by sarahcolbert** [qlu-lab/SUPERGNOVA#5]
Hello,

I have successfully used SUPERGNOVA to calculate local genetic covariance estimates, however now I would like to confirm that those sum up to the total genome-wide genetic covariance. Is the global genetic covariance estimate output by the program, or is there an argument I can use to get this estimate? Sorry if this is not the best place to ask the question since it is not an issue with the program/code, I just wasn't sure of the best way to reach out. 

Thank you in advance for your help!

Best,

Sarah

**Comment by YiliangTracyZhang** [comment]
Hi Sarah,

SUPERGNOVA currently doesn't output global genetic covariance. Our previous method, GNOVA (https://github.com/xtonyjiang/GNOVA) can output global genetic covariance and it has been proved that the global genetic covariance estimation of SUPERGNOVA is almost equivalent to the global genetic covariance of GNOVA. So, I would suggest  you use GNOVA to estimation global genetic covariance.

Thank you.

Best,

Yiliang

**Comment by sarahcolbert** [comment]
Hi Yiliang,

Thank you for getting back to me, I will plan on using GNOVA then. 

Best,

Sarah
