### ISSUE TITLE
Skipping LDscore estimation step!

### ISSUE THREAD

**Issue by msarguru** [qlu-lab/SUPERGNOVA#6]
Hi,

Would be great to have your suggestion on a time-effective way of running sgnova, as I am planning to do it on about 200 traits vs 1 trait of interest. 
For now after using 40 threads, the job takes about 30 minutes, and wondering if there are any ways to do more effectively, for instance using precalculated ldscore (as all are european only analysis).
Any comments/suggestions would be greatly appreciated. 

Regads
msarguru

**Comment by qlu-lab** [comment]
Thank you for your question!

So far we didn't allow the user to use their specified reference panel or LD score. We may include that function in our updated version.
